### ISSUE TITLE
List assets of the user's portfolio

### ISSUE THREAD

**Issue by qdm12** [qdm12/Devops_RESTful#8]
**As a** user
**I need** to list my assets of my portfolio
**So that** I can know what assets I have

**Assumptions**:
- Implemented in the RESTful API
- There is only one portfolio per user

**Acceptance Criteria**
- The assets of a portfolio will be obtained with a GET command to a URL `/api/v1/portfolios/john`

**Comment by bhaveshvasandani** [comment]
I think this should be /api/v1/"portfolios"/"assets"/gold or real estate
since we are assuming one portfolio per user then john would be one of the portfolios who has assests like gold or real estate

**Comment by qdm12** [comment]
First question: why do we actually need the `v1` ? 
Second question: I believe we would have to put the username `john` in the URL right? 
Third question: I understand what you mean for the SINGLE portfolio thing, you're probably right. Any idea how we should separate (or filter) the asset classes in one portfolio?

**Comment by samuelsmithhk** [comment]
1) It's typically best practice to prefix the API with the version number.
Because they're open, we won't have real control over who's using it. If we
change the behaviour of a particular call between say sprint 1 and 2 but
don't prefix with a version, users could end up with unexpected behaviour.

For now, we can just hard code the version number into our paths, it's no
extra work.

2) And, yes, username would be best. When I wrote this, I assumed only one
user for MVP.

3) haven't considered that yet, for the purpose of this story, portfolio
can just be an empty object, or an object with some junk

**Comment by bhaveshvasandani** [comment]
There might be more than 1 portfolios that's why instead of portfolios in the URI it should be replaced {portfolios} which is a variable that accepts various portfolios. For example URI is /api/v1/{portfolios}/{assets}/{assetid} then we can call this by /api/v1/john/commodity/134 or for a different portfolio /api/v1/tom/stock/456.
Another method is to create portfolios: portfolio1, portfolio2,... and in each of them we can assign attributes owner: john or owner: tom.

For NAV we can create a RESTful api by using /api/v1/tom/NAV/ which will directly jsonify all the assets of tom

**Comment by qdm12** [comment]
I have left portfolios in the URI so we can eventually add other paths later on, so I think api/v1/portfolios/john is enough for listing all the assets of John's portfolio (all asset classes together), right ?

**Comment by np1535** [comment]
I think the portfolios do need to kept. This way we know that in the future we could add more user portfolios. The user itself would be a resource then with other CURD operations possible on it.

**Comment by bhaveshvasandani** [comment]
Yes i was thinking over this and your idea is right. Lets stick to the stories that you have created. And do you think more stories should be added? And for NAV are we going to add the values of the assets or just store the navs statically.

**Comment by qdm12** [comment]
I am almost done with a skeleton Python code to store/create/add/remove assets for a portfolio for multiple users, i'll commit it sometime today. You could add a story about implementing a database to store the common information and each user's portfolio. For now I have hard-coded it in the Python code as a dictionary.
